version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: next
    versions:
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.2
  - dependency-name: "@octokit/rest"
    versions:
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
